### PR TITLE
Update

### PR DESCRIPTION
**Pull request by remus32**
I updated dependencies to latest versions, added some useful scalac options, marked BrowserWindow.loadUrl as deprecated and created BrowserWindow.loadURL

### CODE REVIEW

**Comment by bchazalet** [comment]
That looks good. Why is `loadUrl` deprecated in favor of `loadURL`?

**Comment by remus32** [comment]
I don't know, but if you look at the [documentation](http://electron.atom.io/docs/v0.36.5/api/browser-window/), there's only loadURL() method.

**Comment by bchazalet** [comment]
in that case, let's remove `loadUrl` all together rather than deprecate it.

**Comment by bchazalet** [comment]
Great, thanks for your contribution!

**Pull request merged**
